remote_theme: /lanyon

theme: jekyll-theme-minimal
logo: "https://github.com/NYCParks-data/Structures/blob/gh-pages/img/parks_logo.png"

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - index.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
